[project]
name = "office-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.12",
    "mcp[cli]>=1.8.1",
    "requests>=2.32.3",
    "uvicorn>=0.34.2",
]
